### ISSUE TITLE
Publish 1.0.3?

### ISSUE THREAD

**Issue by cwervo** [0ahz/bs-console-qrcode#3]
👋🏼👋🏼👋🏼

Unless I'm misunderstanding it looks like [the npm published version](https://unpkg.com/bs-console-qrcode@1.0.2/index.js) doesn't include [the `small` argument](https://github.com/0ahz/bs-console-qrcode/blob/master/index.js#L10) in the `index.js` in `master`? Would you mind republishing so it uses small by default?

**Comment by 0ahz** [comment]
Released v1.0.3
